# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 09:23
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterestPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('description', models.CharField(max_length=500, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='InterestPointLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='location')),
                ('interest_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heritage.InterestPoint')),
            ],
        ),
    ]
