# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 06:37
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeritageSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('image', models.FileField(upload_to='uploads/')),
                ('location_upper_left', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='location')),
                ('location_lower_right', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='location')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='uploads/')),
                ('caption', models.CharField(max_length=200, verbose_name='caption')),
            ],
        ),
        migrations.CreateModel(
            name='InterestPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('description', models.CharField(max_length=500, verbose_name='description')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='location')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='interest_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.InterestPoint'),
        ),
    ]
