# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 14:39
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_auto_20160807_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heritagesite',
            name='image',
            field=models.FileField(upload_to='./'),
        ),
        migrations.AlterField(
            model_name='heritagesite',
            name='location_lower_right',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name='heritagesite',
            name='location_upper_left',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to='./'),
        ),
    ]
